# Generated by Django 2.2.5 on 2019-10-07 18:18

from django.db import migrations, models
import django.db.models.deletion
import services.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ServiceName_ru', models.CharField(max_length=100, verbose_name='Имя услуги рус')),
                ('ServiceDescription_ru', models.TextField(verbose_name='Описание услуги рус')),
                ('ServiceVideo_ru', models.FileField(blank=True, upload_to=services.models.service_path_video, verbose_name='Видео рус')),
                ('ServiceName_ukr', models.CharField(max_length=100, verbose_name='Имя услуги укр')),
                ('ServiceDescription_ukr', models.TextField(verbose_name='Описание услуги укр')),
                ('ServiceVideo_ukr', models.FileField(blank=True, upload_to=services.models.service_path_video, verbose_name='Видео укр')),
                ('ServiceName_en', models.CharField(max_length=100, verbose_name='Имя услуги англ')),
                ('ServiceDescription_en', models.TextField(verbose_name='Описание услуги англ')),
                ('ServiceVideo_en', models.FileField(blank=True, upload_to=services.models.service_path_video, verbose_name='Видео англ')),
                ('ServiceName_de', models.CharField(max_length=100, verbose_name='Имя услуги нем')),
                ('ServiceDescription_de', models.TextField(verbose_name='Описание услуги нем')),
                ('ServiceVideo_de', models.FileField(blank=True, upload_to=services.models.service_path_video, verbose_name='Видео нем')),
            ],
            options={
                'verbose_name_plural': 'Данные об услугах',
            },
        ),
        migrations.CreateModel(
            name='AddFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ServicePhoto', models.ImageField(blank=True, upload_to=services.models.service_path_photo, verbose_name='Изображение услуги')),
                ('add_media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.Service')),
            ],
            options={
                'verbose_name_plural': 'Картинки для услуг',
            },
        ),
    ]
