# Generated by Django 2.2.5 on 2019-10-07 18:18

from django.db import migrations, models
import django.db.models.deletion
import products.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductName_ru', models.CharField(max_length=100, verbose_name='Имя продукта рус')),
                ('ProductDescription_ru', models.TextField(verbose_name='Описание продукта рус')),
                ('ProductVideo_ru', models.FileField(blank=True, upload_to=products.models.product_path_video, verbose_name='Видео рус')),
                ('ProductName_ukr', models.CharField(max_length=100, verbose_name='Имя продукта укр')),
                ('ProductDescription_ukr', models.TextField(verbose_name='Описание продукта укр')),
                ('ProductVideo_ukr', models.FileField(blank=True, upload_to=products.models.product_path_video, verbose_name='Видео укр')),
                ('ProductName_en', models.CharField(max_length=100, verbose_name='Имя продукта англ')),
                ('ProductDescription_en', models.TextField(verbose_name='Описание продукта англ')),
                ('ProductVideo_en', models.FileField(blank=True, upload_to=products.models.product_path_video, verbose_name='Видео англ')),
                ('ProductName_de', models.CharField(max_length=100, verbose_name='Имя продукта нем')),
                ('ProductDescription_de', models.TextField(verbose_name='Описание продукта нем')),
                ('ProductVideo_de', models.FileField(blank=True, upload_to=products.models.product_path_video, verbose_name='Видео нем')),
            ],
            options={
                'verbose_name_plural': 'Данные о продукте',
            },
        ),
        migrations.CreateModel(
            name='AddFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductPhoto', models.ImageField(blank=True, upload_to=products.models.product_path_photo, verbose_name='Изображение продукта')),
                ('add_media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product')),
            ],
            options={
                'verbose_name_plural': 'Картинки для продуктов',
            },
        ),
    ]
