# Generated by Django 2.2.5 on 2019-10-07 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AboutUs_ru', models.TextField(verbose_name='О нас, рус')),
                ('AboutUs_ukr', models.TextField(verbose_name='О нас, укр')),
                ('AboutUs_en', models.TextField(verbose_name='О нас, англ')),
                ('AboutUs_de', models.TextField(verbose_name='О нас, нем')),
            ],
            options={
                'verbose_name': 'О нас',
                'verbose_name_plural': 'О нас',
            },
        ),
        migrations.CreateModel(
            name='MainPhotos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MainPhoto', models.ImageField(upload_to='media/photos/mainphotos', verbose_name='Изображение для главной страницы')),
                ('add_main_media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainpage.MainPage')),
            ],
            options={
                'verbose_name': 'Картинки для главной',
                'verbose_name_plural': 'Картинки для главной',
            },
        ),
    ]
